
READING THREE TOKENS BNB, STATUSNETWORK, MCAP
```{r}
bnb <- read.table('iTokens/networkbnbTX.txt', sep = " ")
statusnetwork <- read.table('iTokens/networkstatusnetworkTX.txt', sep = " ")
mcap <- read.table('iTokens/networkmcapTX.txt', sep=" ")
library(dplyr)
library(fitdistrplus)
```
NAMING FOUR COLUMNS OF TOKENS
```{r}
names(bnb) <- c('Seller', 'Buyer', 'Time', 'Amount')
names(statusnetwork) <- c('Seller', 'Buyer', 'Time', 'Amount')
names(mcap) <- c('Seller', 'Buyer', 'Time', 'Amount')

```

SUPPLY AND DECIMALS FROM ETHERSCAN.IO
```{r}
supply_bnb <- 183345602.24249
supply_statusnetwork <- 6804870174.8781
supply_mcap <- 100000000
decimals_bnb <- 10^18
decimals_statusnetwork <- 10^18
decimals_mcap <- 10^8
```

FILTERED TOKENS AFTER REMOVING OUTLIERS
```{r}
bnbFiltered <- bnb %>% filter((Amount < decimals_bnb * supply_bnb) & Buyer != 0 & Seller != 0)
statusnetworkFiltered <- statusnetwork %>% filter(Amount < decimals_statusnetwork * supply_statusnetwork)
mcapFiltered <- mcap %>% filter(Amount < decimals_mcap * supply_mcap)
```

CALCULATING NUMBER OF OUTLIERS, TOTAL ROWS, FILTERED TOKENS
```{r}
nrow(bnb)
nrow(bnbFiltered)
bnb %>% filter(Amount >= decimals_bnb * supply_bnb) %>% nrow()

nrow(statusnetwork)
nrow(statusnetworkFiltered)
statusnetwork %>% filter(Amount >= decimals_statusnetwork * supply_statusnetwork) %>% nrow()

nrow(mcap)
nrow(mcapFiltered)
mcap %>% filter(Amount >= decimals_mcap * supply_mcap) %>% nrow()
```


GROUPING BUYERS  
```{r}
buys_bnb.distribution <- bnbFiltered %>% group_by(Buyer) %>% summarise(n = n()) %>% ungroup  
buys_statusnetwork.distribution <- statusnetworkFiltered %>% group_by(Buyer) %>% summarise(n = n()) %>% ungroup
buys_mcap.distribution <- mcapFiltered %>% group_by(Buyer) %>% summarise(n = n()) %>% ungroup
nrow(buys_bnb.distribution)
nrow(buys_bnb.distribution %>% filter(is.na(Buyer)))
nrow(buys_statusnetwork.distribution)
nrow(buys_mcap.distribution)
```

GROUPING BUYER-SELLER PAIRS  
```{r}

users <- bnbFiltered[,1:2]
users
sorted_users <- users %>% filter(Seller <= Buyer)
users_to_swap <- users %>% filter(Seller > Buyer)
users_to_swap[ , c(1,2)] <- users_to_swap[ , c(2,1)]
sorted_users <- merge(sorted_users, users_to_swap)
sorted_users
bs.distribution <- sorted_users %>% group_by(.dots = c("Seller", "Buyer")) %>% count() %>% ungroup
nrow(bs.distribution)



test <- bs.distribution %>% arrange(-n) %>% head(400)
test

bs.distribution %>% group_by(n) %>% summarize(count = n())

test <- test %>% group_by(n) %>% summarize(count = n())
test %>% arrange(-count) %>% head(400)


test <- bs.distribution %>% filter(n > 3 & n < 300)
test %>% filter(Seller == 5)
nrow(test)
test


# fit <- fitdistr(test$n, densfun="normal")  # we assume my_data ~ Normal(?,?)
# fit

# test %>% group_by(n) %>% summarize(count = n())


fit <- fitdistr(test$n, densfun="normal")  # we assume my_data ~ Normal(?,?)
lnfit <- fitdist(test$n, 'lnorm')
expfit <- fitdist(test$n, 'exp')
gammafit <- fitdist(test$n, 'gamma', lower = c(0, 0), start = list(scale = 1, shape = 1))
nbinfit <- fitdist(test$n, 'nbinom')


hist(test$n, pch=20, breaks=25, prob=TRUE, main="")
curve(dnorm(x, lnfit$estimate[1], lnfit$estimate[2]), col="blue", lwd=1, add=T)


curve(dnorm(x, fit$estimate[1], fit$estimate[2]), col="red", lwd=2, add=T)
curve(dnorm(x, expfit$estimate[1], expfit$estimate[2]), col="green", lwd=2, add=T)
curve(dnorm(x, gammafit$estimate[1], gammafit$estimate[2]), col="orange", lwd=2, add=T)
curve(dnorm(x, nbinfit$estimate[1], nbinfit$estimate[2]), col="black", lwd=2, add=T)


```

TESTING 
```{r}
tail(buys_bnb.distribution[order(Buyer),], 100)

library(fitdistrplus)


test <- bnbFiltered %>% group_by(Buyer) %>% summarise(n = n()) %>% filter(Buyer == 0)
test[order(Buyer),]

bnbFiltered %>% filter(Buyer == 0)

buys.distribution %>% filter(is.na(n))


set.seed(101)
my_data <- rnorm(250, mean=1, sd=0.45)      # unkonwn distribution parameters
fit <- fitdistr(my_data, densfun="normal")  # we assume my_data ~ Normal(?,?)
fit


test <- buys_bnb.distribution %>% arrange(-n) %>% head(400)
test

test <- buys_bnb.distribution %>% filter( n < 260 & n > 6)
test
nrow(test)

fit <- fitdistr(test$n, densfun="normal")  # we assume my_data ~ Normal(?,?)
fit

# test %>% group_by(n) %>% summarize(count = n())


fit <- fitdistr(test$n, densfun="normal")  # we assume my_data ~ Normal(?,?)
lnfit <- fitdist(test$n, 'lnorm')
fit.exp.buy_bnb <- fitdist(test$n, 'exp')
fit.gamma.buy_bnb <- fitdist(test$n, 'gamma', lower = c(0, 0), start = list(scale = 1, shape = 1))
fit.nbinom.buy_bnb <- fitdist(test$n, 'nbinom')

# library(scales)

# rescale(test$n, to =c(1,300))


hist(test$n, pch=20, breaks=25, prob=TRUE, main="")

curve(dnorm(x, fit$estimate[1], fit$estimate[2]), col="red", lwd=2, add=T)
curve(dnorm(x, lnfit$estimate[1], lnfit$estimate[2]), col="blue", lwd=2, add=T)
curve(dnorm(x, fit.exp.buy_bnb$estimate[1], fit.exp.buy_bnb$estimate[2]), col="green", lwd=2, add=T)
curve(dnorm(x, fit.gamma.buy_bnb$estimate[1], fit.gamma.buy_bnb$estimate[2]), col="orange", lwd=2, add=T)
curve(dnorm(x, fit.nbinom.buy_bnb$estimate[1], fit.nbinom.buy_bnb$estimate[2]), col="black", lwd=2, add=T)


# curve(dnorm(x, fit$estimate[1], fit$estimate[2]), col="red", lwd=2, add=T)
```


GROUPING SELLERS
```{r}
sells_bnb.distribution <- bnbFiltered %>% group_by(Seller) %>% summarise(n = n()) %>% ungroup
sells_statusnetwork.distribution <- statusnetworkFiltered %>% group_by(Seller) %>% summarise(n = n()) %>% ungroup
sells_mcap.distribution <- mcapFiltered %>% group_by(Seller) %>% summarise(n = n()) %>% ungroup
nrow(sells_bnb.distribution)
nrow(sells_statusnetwork.distribution)
nrow(sells_mcap.distribution)
```
```{r}
library(fitdistrplus)
descdist(sells_bnb.distribution$n, discrete = TRUE)
```

DISTRIBUTION OF BUYERS AND SELLERS FOR BNB 
```{r}
fit.exp.buy_bnb <- fitdist(buys_bnb.distribution$n, 'exp')
fit.gamma.buy_bnb <- fitdist(buys_bnb.distribution$n, 'gamma', lower = c(0, 0), start = list(scale = 1, shape = 1))
fit.geometric.buy_bnb <- fitdist(buys_bnb.distribution$n, 'geom')
fit.log.buy_bnb <- fitdist(buys_bnb.distribution$n, 'logis')
fit.lnorm.buy_bnb <- fitdist(buys_bnb.distribution$n, 'lnorm')
fit.nbinom.buy_bnb <- fitdist(buys_bnb.distribution$n, 'nbinom')
fit.norm.buy_bnb <- fitdist(buys_bnb.distribution$n, 'norm')
fit.pois.buy_bnb <- fitdist(buys_bnb.distribution$n, 'pois')
fit.unif.buy_bnb <- fitdist(buys_bnb.distribution$n, 'unif')
fit.weibull.buy_bnb <- fitdist(buys_bnb.distribution$n, 'weibull')

plot(fit.exp.buy_bnb)


fit.exp.sell_bnb <- fitdist(sells_bnb.distribution$n, 'exp')
fit.gamma.sell_bnb <- fitdist(sells_bnb.distribution$n, 'gamma', lower = c(0, 0), start = list(scale = 1, shape = 1))
fit.geometric.sell_bnb <- fitdist(sells_bnb.distribution$n, 'geom')
fit.log.sell_bnb <- fitdist(sells_bnb.distribution$n, 'logis')
fit.lnorm.sell_bnb <- fitdist(sells_bnb.distribution$n, 'lnorm')
fit.nbinom.sell_bnb <- fitdist(sells_bnb.distribution$n, 'nbinom')
fit.norm.sell_bnb <- fitdist(sells_bnb.distribution$n, 'norm')
fit.pois.sell_bnb <- fitdist(sells_bnb.distribution$n, 'pois')
fit.unif.sell_bnb <- fitdist(sells_bnb.distribution$n, 'unif')
fit.weibull.sell_bnb <- fitdist(sells_bnb.distribution$n, 'weibull')

gofstat(list(fit.weibull.buy_bnb, fit.gamma.buy_bnb, fit.lnorm.buy_bnb, fit.exp.buy_bnb, fit.log.buy_bnb, fit.geometric.buy_bnb, fit.nbinom.buy_bnb, fit.norm.buy_bnb, fit.pois.buy_bnb, fit.unif.buy_bnb))
gofstat(list(fit.weibull.sell_bnb, fit.gamma.sell_bnb, fit.lnorm.sell_bnb, fit.exp.sell_bnb, fit.log.sell_bnb, fit.geometric.sell_bnb, fit.nbinom.sell_bnb, fit.norm.sell_bnb, fit.pois.sell_bnb, fit.unif.sell_bnb))
```


Part 2

```{r}

statusnetworkPrice = read.table(file="prices/statusnetwork", header=T,sep="\t")
bnbPrice = read.table(file="prices/bnb.csv", header=T,sep=",")
mcapPrice = read.table(file="prices/mcap", header=T,sep="\t")
colNames <- c("Date","Open","High","Low", "Close" ,"Volume","MarketCap")
colnames(statusnetworkPrice) <- colNames
colnames(bnbPrice) <- colNames
colnames(mcapPrice) <- colNames
bnbPrice
mcapPrice
statusnetworkPrice

bnbFiltered


colnames(bnbFiltered)<-c("FromNodeId", "ToNodeId", "Unixdate", "TokenAmount")

bnbPrice$Date<-as.Date(bnbPrice$Date,format="%m/%d/%Y")
bnbPrice$Date<- as.Date(as.POSIXct(bnbPrice$Date, origin="1970-01-01"))
bnbFiltered$Unixdate<- as.Date(as.POSIXct(bnbFiltered$Unixdate, origin="1970-01-01")) 

bnbFiltered

#Print statusnetwork Data
head(bnbPrice)
head(bnbFiltered)

# bnbFiltered[, 2]

#bnb buys
buys.distribution.bnb  <- bnbFiltered %>% group_by(ToNodeId) %>% summarise(n = n()) %>% ungroup 
colnames(buys.distribution.bnb) <- c("BuyerId","Frequency_of_buys")
sortedBNB_Buyer <- buys.distribution.bnb[order(-buys.distribution.bnb$Frequency_of_buys),]

#most active buyerId and no of times the buyer bought the token
head(sortedBNB_Buyer,1)

#bnb sells
sells.distribution.bnb  <- bnbFiltered %>% group_by(FromNodeId) %>% summarise(n = n()) %>% ungroup 
colnames(sells.distribution.bnb) <- c("SellerId","Frequency_of_sells")
sortedBNB_Seller <- sells.distribution.bnb[order(-sells.distribution.bnb$Frequency_of_sells),]

sortedBNB_Seller


#---Regression---
filteredstatusnetwork <- bnbFiltered[order(-bnbFiltered$TokenAmount),]

bnbRegression <- merge(bnbFiltered, bnbPrice, by.x="Unixdate", by.y="Date")

lm.fit.bnb= lm(Low ~ TokenAmount + Open, data= bnbRegression)
summary(lm.fit.bnb)

plot(lm.fit.bnb)

```

